CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS subs(
    id          VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    account_id  VARCHAR NOT NULL,
    name VARCHAR NOT NULL
);
